version: '3.8'

services:
  python-app:
    build: .
    container_name: benchmark
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python3